name: 'OilMod-Test'
version: 0.0.1
description: 'OilMod Api Test'
author: sirati97
main: org.oilmod.test.plugin1.TestPlugin
load: STARTUP
commands:
    oilmodtest:
        description: 'Test command'
        aliases: ['omt']
    invsee:
        description: 'Advanced invsee command'
        useage: '<command> <player>'
        aliases: ['inv']